name: ${name}
version: ${version}
main: ${group}.${name.toLowerCase()}.${name}
api-version: '${MinecraftVersion}'
author: Blugon
libraries:
  - ${invfx}
  - ${kommand}
  - ${tab}
  - org.jetbrains.kotlin:kotlin-stdlib:${KotlinVersion}
  - org.jetbrains.kotlin:kotlin-reflect:${KotlinVersion}